'use strict';

module.exports = {
  up: function (queryInterface, Sequelize) {
    return queryInterface.bulkInsert('players', [
      { name: "Midas", guildId: 1, positionId: 1 },
      { name: "Smoke", guildId: 1, positionId: 1 },
      { name: "Flask", guildId: 1, positionId: 2 },
      { name: "Naja", guildId: 1, positionId: 2 },
      { name: "Calculus", guildId: 1, positionId: 3 },
      { name: "Compound", guildId: 1, positionId: 3 },
      { name: "Katalyst", guildId: 1, positionId: 3 },
      { name: "Mercury", guildId: 1, positionId: 3 },
      { name: "Venin", guildId: 1, positionId: 3 },
      { name: "Katalyst (veteran)", guildId: 1, positionId: 3 },
      { name: "Vitriol", guildId: 1, positionId: 3 },
      { name: "Esters", guildId: 2, positionId: 1 },
      { name: "Tapper", guildId: 2, positionId: 1 },
      { name: "Scum", guildId: 2, positionId: 2 },
      { name: "Quaff", guildId: 2, positionId: 2 },
      { name: "Friday", guildId: 2, positionId: 3 },
      { name: "Hooper", guildId: 2, positionId: 3 },
      { name: "Mash", guildId: 2, positionId: 3 },
      { name: "Spigot", guildId: 2, positionId: 3 },
      { name: "Stave", guildId: 2, positionId: 3 },
      { name: "Stoker", guildId: 2, positionId: 3 },
      { name: "Spigot (veteran)", guildId: 2, positionId: 3 },
      { name: "Fillet", guildId: 3, positionId: 1 },
      { name: "Ox", guildId: 3, positionId: 1 },
      { name: "Princess", guildId: 3, positionId: 2 },
      { name: "Truffles", guildId: 3, positionId: 2 },
      { name: "Boar", guildId: 3, positionId: 3 },
      { name: "Boiler", guildId: 3, positionId: 3 },
      { name: "Brisket", guildId: 3, positionId: 3 },
      { name: "Meathook", guildId: 3, positionId: 3 },
      { name: "Shank", guildId: 3, positionId: 3 },
      { name: "Tenderizer", guildId: 3, positionId: 3 },
      { name: "Brisket (veteran)", guildId: 3, positionId: 3 },
      { name: "Ballista", guildId: 4, positionId: 1 },
      { name: "Pin Vice", guildId: 4, positionId: 1 },
      { name: "Mainspring", guildId: 4, positionId: 2 },
      { name: "Mother", guildId: 4, positionId: 2 },
      { name: "Colossus", guildId: 4, positionId: 3 },
      { name: "Compound", guildId: 4, positionId: 3 },
      { name: "Hoist", guildId: 4, positionId: 3 },
      { name: "Ratchet", guildId: 4, positionId: 3 },
      { name: "Salvo", guildId: 4, positionId: 3 },
      { name: "Velocity", guildId: 4, positionId: 3 },
      { name: "Velocity (veteran)", guildId: 4, positionId: 3 },
      { name: "Tater", guildId: 5, positionId: 3 },
      { name: "Corsair", guildId: 6, positionId: 1 },
      { name: "Shark", guildId: 6, positionId: 1 },
      { name: "Salt", guildId: 6, positionId: 2 },
      { name: "Tentacles", guildId: 6, positionId: 2 },
      { name: "Angel", guildId: 6, positionId: 3 },
      { name: "Greyscales", guildId: 6, positionId: 3 },
      { name: "Jac", guildId: 6, positionId: 3 },
      { name: "Kraken", guildId: 6, positionId: 3 },
      { name: "Sakana", guildId: 6, positionId: 3 },
      { name: "Siren", guildId: 6, positionId: 3 },
      { name: "Siren (veteran)", guildId: 6, positionId: 3 },
      { name: "Theron", guildId: 7, positionId: 1 },
      { name: "Fahad", guildId: 7, positionId: 2 },
      { name: "Chaska", guildId: 7, positionId: 3 },
      { name: "Egret", guildId: 7, positionId: 3 },
      { name: "Hearne", guildId: 7, positionId: 3 },
      { name: "Jaecar", guildId: 7, positionId: 3 },
      { name: "Seenah", guildId: 7, positionId: 3 },
      { name: "Zarola", guildId: 7, positionId: 3 },
      { name: "Hammer", guildId: 8, positionId: 1 },
      { name: "Honour", guildId: 8, positionId: 1 },
      { name: "Marbles", guildId: 8, positionId: 2 },
      { name: "Wrecker", guildId: 8, positionId: 2 },
      { name: "Brick", guildId: 8, positionId: 3 },
      { name: "Chisel", guildId: 8, positionId: 3 },
      { name: "Flint", guildId: 8, positionId: 3 },
      { name: "Harmony", guildId: 8, positionId: 3 },
      { name: "Mallet", guildId: 8, positionId: 3 },
      { name: "Tower", guildId: 8, positionId: 3 },
      { name: "Harmony (veteran)", guildId: 8, positionId: 3 },
      { name: "Obulus", guildId: 9, positionId: 1 },
      { name: "Scalpel", guildId: 9, positionId: 1 },
      { name: "Dirge", guildId: 9, positionId: 2 },
      { name: "Vileswarm", guildId: 9, positionId: 2 },
      { name: "Bonesaw", guildId: 9, positionId: 3 },
      { name: "Casket", guildId: 9, positionId: 3 },
      { name: "Cosset", guildId: 9, positionId: 3 },
      { name: "Ghast", guildId: 9, positionId: 3 },
      { name: "Graves", guildId: 9, positionId: 3 },
      { name: "Silence", guildId: 9, positionId: 3 },
      { name: "Graves (veteran)", guildId: 9, positionId: 3 },
      { name: "Blackheart", guildId: 10, positionId: 1 },
      { name: "Rage (veteran)", guildId: 10, positionId: 1 },
      { name: "Coin", guildId: 10, positionId: 2 },
      { name: "Strongbox", guildId: 10, positionId: 2 },
      { name: "Avarisse", guildId: 10, positionId: 3 },
      { name: "Decimate", guildId: 10, positionId: 3 },
      { name: "Fangtooth", guildId: 10, positionId: 3 },
      { name: "Greede", guildId: 10, positionId: 3 },
      { name: "Gutter", guildId: 10, positionId: 3 },
      { name: "Harry \"The Hat\"", guildId: 10, positionId: 3 },
      { name: "Hemlocke", guildId: 10, positionId: 3 },
      { name: "Minx", guildId: 10, positionId: 3 },
      { name: "Mist", guildId: 10, positionId: 3 },
      { name: "Rage", guildId: 10, positionId: 3 },
      { name: "Snakeskin", guildId: 10, positionId: 3 }
    ], {});
  },

  down: function (queryInterface, Sequelize) {
    return queryInterface.bulkDelete('players', null, {});
  }
};
